### ISSUE TITLE
Connected -Scheduled invalid date 

### ISSUE THREAD

**Issue by rkon189** [mattdy/MMM-TeslaFi#33]
Connected "item" shows "scheduled invalid date"
Is this a bug or did I miss a setting in config for this to work?

**Comment by rkon189** [comment]
I think this is what is used for that; TeslaFi is providing: scheduled_charging_start_time":"[1658385000]

**Comment by mattdy** [comment]
Thanks for the report - it looks like TeslaFi is returning an array rather than a number for `scheduled_charging_start_time`, which is probably why this isn't working.

Would you be happy to provide a full dump of the TeslaFi data from when you have a charge scheduled? You can remove the VIN and any other personally identifiable information if you wish. I don't use scheduled charging myself, so can't replicate the issue.

Thanks

**Comment by rkon189** [comment]
TeslaFi output, some items "REMOVED" (note, my scheduled charging time is 0130 am (central US):

**Comment by mattdy** [comment]
Thanks - I think this was caused by `moment.js` not parsing a unix time stamp correctly when passed as a string.

I've provided an update which should hopefully sort this, could you please test & verify? The only potential issue I can see here is the difference between UTC and your local time, but I don't have a way of testing that, so please open another issue if the correct time still isn't shown.
