### ISSUE TITLE
TeslaFi items removal 

### ISSUE THREAD

**Issue by rkon189** [mattdy/MMM-TeslaFi#43]
Not able to remove/edit which items appear while using TeslaFi api in new update. When using items or apicommand in config, all data points still appear.

**Comment by mattdy** [comment]
I'm sorry about that - entirely possible something got broken when the new functionality was added.

Could you please provide a copy of your configuration (with API keys redacted) for me to test?

Thanks!

**Comment by rkon189** [comment]
{
		    module: "MMM-Tesla",
		    position: "top_left",
		    config: {
                     source: {
                      name: "teslafi",
		      apiKey: "removed",
		      apiCommand: [ 'charge-time', 'charge-added', 'charge-power', 'temperature', 'version-new', 'data-time'],
		              } 
		            }
		  },

**Comment by mattdy** [comment]
I think the issue here is with your configuration - the `apiCommand` entry within `source` relates to which data set to pull from TeslaFi - you can see more details [here](https://teslafi.com/api.php).

In order to set which fields to show, you should use the `items` entry within the main configuration - this doesn't sit within `source`. Your configuration should look something like this:

```
{
   module: "MMM-Tesla",
   position: "top_left",
   config: {
      source: {
         name: "teslafi",
         apiKey: "removed",
         apiCommand: 'lastGoodTemp',
      },
      items: [ 'charge-time', 'charge-added', 'charge-power', 'temperature', 'version-new', 'data-time'],
   }
},
```

Please let me know how you get on, and if you need any more help setting this up.
